webtalk_init -webtalk_dir D:/ComDesignExp/EX3/EX3/EX3.sim/sim_1/behav/xsim/xsim.dir/mycpu_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jun 27 20:50:46 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bb8dd84f-447a-4163-bb82-de867ff0df26" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5f761caa58a245fe802dc2ca18b36310" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "226" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "161818273 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9988_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3240587455 -regid "" -xml D:/ComDesignExp/EX3/EX3/EX3.sim/sim_1/behav/xsim/xsim.dir/mycpu_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/ComDesignExp/EX3/EX3/EX3.sim/sim_1/behav/xsim/xsim.dir/mycpu_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/ComDesignExp/EX3/EX3/EX3.sim/sim_1/behav/xsim/xsim.dir/mycpu_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
